package expo.modules.laypwidget

// Resource ids of the calendar widget's month grid, in reading order
// (generated from res/layout/layp_widget_calendar.xml: 6 rows x 7 cells).
// Each cell is a small row: the day number plus two icon slots for the marks.
object CalendarIds {
  val CELLS = intArrayOf(R.id.layp_cal_c0, R.id.layp_cal_c1, R.id.layp_cal_c2, R.id.layp_cal_c3, R.id.layp_cal_c4, R.id.layp_cal_c5, R.id.layp_cal_c6, R.id.layp_cal_c7, R.id.layp_cal_c8, R.id.layp_cal_c9, R.id.layp_cal_c10, R.id.layp_cal_c11, R.id.layp_cal_c12, R.id.layp_cal_c13, R.id.layp_cal_c14, R.id.layp_cal_c15, R.id.layp_cal_c16, R.id.layp_cal_c17, R.id.layp_cal_c18, R.id.layp_cal_c19, R.id.layp_cal_c20, R.id.layp_cal_c21, R.id.layp_cal_c22, R.id.layp_cal_c23, R.id.layp_cal_c24, R.id.layp_cal_c25, R.id.layp_cal_c26, R.id.layp_cal_c27, R.id.layp_cal_c28, R.id.layp_cal_c29, R.id.layp_cal_c30, R.id.layp_cal_c31, R.id.layp_cal_c32, R.id.layp_cal_c33, R.id.layp_cal_c34, R.id.layp_cal_c35, R.id.layp_cal_c36, R.id.layp_cal_c37, R.id.layp_cal_c38, R.id.layp_cal_c39, R.id.layp_cal_c40, R.id.layp_cal_c41)
  val TEXTS = intArrayOf(R.id.layp_cal_t0, R.id.layp_cal_t1, R.id.layp_cal_t2, R.id.layp_cal_t3, R.id.layp_cal_t4, R.id.layp_cal_t5, R.id.layp_cal_t6, R.id.layp_cal_t7, R.id.layp_cal_t8, R.id.layp_cal_t9, R.id.layp_cal_t10, R.id.layp_cal_t11, R.id.layp_cal_t12, R.id.layp_cal_t13, R.id.layp_cal_t14, R.id.layp_cal_t15, R.id.layp_cal_t16, R.id.layp_cal_t17, R.id.layp_cal_t18, R.id.layp_cal_t19, R.id.layp_cal_t20, R.id.layp_cal_t21, R.id.layp_cal_t22, R.id.layp_cal_t23, R.id.layp_cal_t24, R.id.layp_cal_t25, R.id.layp_cal_t26, R.id.layp_cal_t27, R.id.layp_cal_t28, R.id.layp_cal_t29, R.id.layp_cal_t30, R.id.layp_cal_t31, R.id.layp_cal_t32, R.id.layp_cal_t33, R.id.layp_cal_t34, R.id.layp_cal_t35, R.id.layp_cal_t36, R.id.layp_cal_t37, R.id.layp_cal_t38, R.id.layp_cal_t39, R.id.layp_cal_t40, R.id.layp_cal_t41)
  val ICON_A = intArrayOf(R.id.layp_cal_a0, R.id.layp_cal_a1, R.id.layp_cal_a2, R.id.layp_cal_a3, R.id.layp_cal_a4, R.id.layp_cal_a5, R.id.layp_cal_a6, R.id.layp_cal_a7, R.id.layp_cal_a8, R.id.layp_cal_a9, R.id.layp_cal_a10, R.id.layp_cal_a11, R.id.layp_cal_a12, R.id.layp_cal_a13, R.id.layp_cal_a14, R.id.layp_cal_a15, R.id.layp_cal_a16, R.id.layp_cal_a17, R.id.layp_cal_a18, R.id.layp_cal_a19, R.id.layp_cal_a20, R.id.layp_cal_a21, R.id.layp_cal_a22, R.id.layp_cal_a23, R.id.layp_cal_a24, R.id.layp_cal_a25, R.id.layp_cal_a26, R.id.layp_cal_a27, R.id.layp_cal_a28, R.id.layp_cal_a29, R.id.layp_cal_a30, R.id.layp_cal_a31, R.id.layp_cal_a32, R.id.layp_cal_a33, R.id.layp_cal_a34, R.id.layp_cal_a35, R.id.layp_cal_a36, R.id.layp_cal_a37, R.id.layp_cal_a38, R.id.layp_cal_a39, R.id.layp_cal_a40, R.id.layp_cal_a41)
  val ICON_B = intArrayOf(R.id.layp_cal_b0, R.id.layp_cal_b1, R.id.layp_cal_b2, R.id.layp_cal_b3, R.id.layp_cal_b4, R.id.layp_cal_b5, R.id.layp_cal_b6, R.id.layp_cal_b7, R.id.layp_cal_b8, R.id.layp_cal_b9, R.id.layp_cal_b10, R.id.layp_cal_b11, R.id.layp_cal_b12, R.id.layp_cal_b13, R.id.layp_cal_b14, R.id.layp_cal_b15, R.id.layp_cal_b16, R.id.layp_cal_b17, R.id.layp_cal_b18, R.id.layp_cal_b19, R.id.layp_cal_b20, R.id.layp_cal_b21, R.id.layp_cal_b22, R.id.layp_cal_b23, R.id.layp_cal_b24, R.id.layp_cal_b25, R.id.layp_cal_b26, R.id.layp_cal_b27, R.id.layp_cal_b28, R.id.layp_cal_b29, R.id.layp_cal_b30, R.id.layp_cal_b31, R.id.layp_cal_b32, R.id.layp_cal_b33, R.id.layp_cal_b34, R.id.layp_cal_b35, R.id.layp_cal_b36, R.id.layp_cal_b37, R.id.layp_cal_b38, R.id.layp_cal_b39, R.id.layp_cal_b40, R.id.layp_cal_b41)
  val ROWS = intArrayOf(R.id.layp_cal_row0, R.id.layp_cal_row1, R.id.layp_cal_row2, R.id.layp_cal_row3, R.id.layp_cal_row4, R.id.layp_cal_row5)
  val WEEKDAYS = intArrayOf(R.id.layp_cal_w0, R.id.layp_cal_w1, R.id.layp_cal_w2, R.id.layp_cal_w3, R.id.layp_cal_w4, R.id.layp_cal_w5, R.id.layp_cal_w6)
}
