import React, { createContext, useContext } from "react";

export const LIGHT = {
  bg: "#F3F4F0", card: "#FFFFFF",
  text: "#121212", textMuted: "#6F7786",
  line: "#E4E5DF",
  // accentDark is a "solid accent surface" (hero cards, round buttons,
  // primary CTAs) that is ALWAYS paired with white text/icons, so it must
  // stay dark in both themes -- never white.
  accentDark: "#17203A",
  // Dark-gray solid surface for toggles / active states that aren't CTAs.
  neutralDark: "#3A3A3A",
  glass: "#FFFFFF",
  glassBorder: "#E4E5DF",
  glassHighlight: "rgba(0,0,0,0.04)",
};

export const DARK = {
  bg: "#101010", card: "#1A1A1A", text: "#EDEDF0",
  textMuted: "#A8A8B0",
  line: "#2C2C2C",
  // Must remain a dark indigo: white text sits on top of it. A white value
  // here made every hero card / CTA button unreadable in dark mode.
  accentDark: "#2E3E72",
  neutralDark: "#3A3A3A",
  glass: "#1A1A1A",
  glassBorder: "#2C2C2C",
  glassHighlight: "rgba(255,255,255,0.08)",
};

// Mid-tone accents: each one is readable on both light and dark surfaces and
// still carries white text when used as a filled button/background.
export const ACCENT = {
  primary: "#3E63D1",
  gold: "#D9A441", leaf: "#3E7C59", ember: "#D1573F",
  sky: "#3E63D1", plum: "#8B5FBF", teal: "#2F9E9E",
  rose: "#D1477F", slate: "#5C6B8A",
};
export const PALETTE = [ACCENT.gold, ACCENT.leaf, ACCENT.ember, ACCENT.sky, ACCENT.plum, ACCENT.teal];

export const WEEKDAYS = [
  { id: 2, label: "Mon" },
  { id: 3, label: "Tue" },
  { id: 4, label: "Wed" },
  { id: 5, label: "Thu" },
  { id: 6, label: "Fri" },
  { id: 7, label: "Sat" },
  { id: 1, label: "Sun" },
];

// Seed data only -- the live account list is now user-managed state
// (add/rename/remove named accounts like GCash, Maya, Wallet), stored and
// passed down from App.js, same pattern as budget splits.
// interestRate (% per year, accrued daily -- same mechanic as
// DEFAULT_SAVINGS_ACCOUNTS below) lets a regular budget account earn
// interest on its own, e.g. a Maribank account used for everyday spending
// that still gains interest without the money ever being moved into a
// separate savings account. Left at 0 for the seed accounts; the account's
// own edit row is where a real rate gets filled in.
export const DEFAULT_ACCOUNTS = [
  { id: "ecash", label: "E-cash", color: ACCENT.sky, interestRate: 0 },
  { id: "physical", label: "Physical", color: ACCENT.gold, interestRate: 0 },
];

// Named savings destinations -- e.g. "this specific money is sitting in
// GoTyme, earning its own interest" instead of one undifferentiated
// savings pool. Seeded with the two banks mentioned, but with
// interestRate left at 0 rather than guessing a real-world rate: digital
// bank promo rates change often enough that hard-coding a number here
// would likely just be wrong by the time anyone reads it -- the account's
// own edit screen is where the person fills in whatever their actual
// current rate is.
export const DEFAULT_SAVINGS_ACCOUNTS = [
  { id: "gotyme", name: "GoTyme", color: ACCENT.teal, interestRate: 0 },
  { id: "maribank", name: "Maribank", color: ACCENT.sky, interestRate: 0 },
];

// One-tap starting points for the two rate structures people actually
// asked for by name, editable afterward like any other rate -- these are
// promo rates as of when this was written and WILL drift, so applying a
// preset is a starting point, not a promise; the account's own rate
// field is still the source of truth and can be typed over any time.
// GoTyme's posted savings rate is flat regardless of balance. Maribank's
// is tiered and applied per bracket (the first ₱1M earns the lower rate,
// only the portion above ₱1M earns the higher one) -- not "the whole
// balance jumps to the higher rate once you cross ₱1M". The top
// bracket's `upTo` uses a large finite number rather than Infinity --
// interestTiers gets saved to AsyncStorage as JSON, and JSON.stringify
// silently turns Infinity into null, which would corrupt the tier on
// the very next app reload.
const UNBOUNDED = 999999999999;
export const INTEREST_PRESETS = [
  { id: "gotyme", label: "GoTyme (3.00% flat)", interestRate: 3.0, interestTiers: null },
  { id: "maribank", label: "Maribank (3.25% / 3.75% > \u20B11M)", interestRate: 3.25, interestTiers: [{ upTo: 1000000, rate: 3.25 }, { upTo: UNBOUNDED, rate: 3.75 }] },
];

export const CATEGORIES = [
  { id: "school", label: "School", color: ACCENT.sky },
  { id: "errands", label: "Errands", color: ACCENT.leaf },
  { id: "shopping", label: "Shopping", color: ACCENT.gold },
  { id: "other", label: "Other", color: ACCENT.plum },
];

export const INCOME_CATEGORIES = [
  { id: "allowance", label: "Allowance", color: ACCENT.leaf },
  { id: "salary", label: "Salary", color: ACCENT.sky },
  { id: "gift", label: "Gift", color: ACCENT.gold },
  { id: "refund", label: "Refund", color: ACCENT.teal },
  // Auto-generated by accrueAccountInterest (see utils.ts) whenever an
  // interest-bearing budget account gains its daily interest -- included
  // here so it gets a real label/color anywhere moneyLog categories are
  // displayed (Activity pie chart, etc.) instead of falling back to
  // "Other".
  { id: "interest", label: "Interest", color: ACCENT.rose },
  { id: "other", label: "Other", color: ACCENT.plum },
];

// Quick-pick categories for what an expense was actually *for* (food,
// transportation, etc.) -- distinct from the budget split it's charged
// against (Needs/Wants/Savings). A split says which bucket of your income
// paid for something; this says what it was. Stored in the same free-text
// `expense.label` field ExpenseForm already had, so picking one of these
// just fills that field instead of requiring the user to type it --
// custom labels typed by hand still work exactly as before.
export const SPENDING_LABELS = [
  { id: "food", label: "Food", color: ACCENT.gold },
  { id: "transportation", label: "Transportation", color: ACCENT.sky },
  { id: "school", label: "School", color: ACCENT.rose },
  { id: "bills", label: "Bills", color: ACCENT.ember },
  { id: "shopping", label: "Shopping", color: ACCENT.teal },
  { id: "entertainment", label: "Entertainment", color: ACCENT.leaf },
  { id: "health", label: "Health", color: ACCENT.slate },
  { id: "other", label: "Other", color: ACCENT.plum },
];

export const DEFAULT_SPLITS = {
  "50-30-20": [
    { id: "s0", label: "Needs", percent: 50, color: ACCENT.sky },
    { id: "s1", label: "Wants", percent: 30, color: ACCENT.gold },
    { id: "s2", label: "Savings", percent: 20, color: ACCENT.leaf },
  ],
  "70-20-10": [
    { id: "s0", label: "Needs", percent: 70, color: ACCENT.sky },
    { id: "s1", label: "Wants", percent: 20, color: ACCENT.gold },
    { id: "s2", label: "Savings", percent: 10, color: ACCENT.leaf },
  ],
};

// Daily Budget Review defaults -- notification on, review at 10 PM, same
// spirit as the spec's example default.
export const DEFAULT_DAILY_BUDGET_SETTINGS = { enabled: true, time: "22:00" };

// School feature -- applied to newly created subjects unless the user
// overrides them per-subject in the Add/Edit Subject form.
export const DEFAULT_SCHOOL_DEFAULTS = {
  classReminderEnabled: true,
  advanceReminderEnabled: true,
  advanceReminderMinutes: 10,
  classCheckInEnabled: true,
  classCheckInMinutes: 60,
};
export const ADVANCE_REMINDER_OPTIONS = [5, 10, 15, 30, 60];
// Options for "Do you have class today?" -- how long before the class
// itself this lighter heads-up fires. Was previously a fixed 60 minutes;
// now configurable per subject the same way advance-reminder minutes are.
export const CHECKIN_REMINDER_OPTIONS = [30, 45, 60, 90, 120];
export const EVENT_TYPES = [
  { id: "assignment", label: "Assignment" },
  { id: "quiz", label: "Quiz" },
  { id: "exam", label: "Exam" },
  { id: "lab", label: "Laboratory" },
  { id: "project", label: "Project" },
  { id: "presentation", label: "Presentation" },
  { id: "other", label: "Other" },
];

export const ThemeContext = createContext({ theme: LIGHT, dark: false });
export const useTheme = () => useContext(ThemeContext);
